basePath: /
definitions:
  models.User:
    properties:
      created_at:
        type: string
      id:
        type: integer
      updated_at:
        type: string
      username:
        type: string
    type: object
host: localhost:8181
info:
  contact: {}
  description: API de base pour jeu en Go
  title: Gowebgame API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: Affiche un message de bienvenue
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Accueil
      tags:
      - Accueil
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Crée un nouveau compte utilisateur avec un identifiant unique et
        un mot de passe
      parameters:
      - description: Informations de l'utilisateur
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Message de confirmation
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Erreur de validation
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Erreur serveur ou utilisateur déjà existant
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Inscription utilisateur
      tags:
      - Authentification
swagger: "2.0"
